name: GitHub Snake

# Schedule the workflow to run daily at midnight UTC
on:
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3

        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}

          # Define the output files and their configurations
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=#d68c6d

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output

          # Optionally, you can set a custom commit message
          commit_message: "update snake"
