name: Github Stats

# Schedule the workflow to run daily at midnight UTC
on:
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Step 2: Generate readme stats
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: '{"username":"UmbrellaLeaf5","show_icons":true,"theme":"dark","show":["reviews","discussions_started","discussions_answered","prs_merged","prs_merged_percentage"]}'
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true
          commit_message: "update stats"
